### ISSUE TITLE
Type parameters redefined by RM specification are not displayed correctly

### ISSUE THREAD

**Issue by serefarikan** [openEHR/adl-tools#7]
Some types under the quantity package (such as DV_COUNT) redefine type parameters for normal_range and other_reference ranges to more specific types (the actual type that inherits these attributes)

However, the properties and closure views still show the less strict type bound as follows:

![image](https://cloud.githubusercontent.com/assets/1894220/18832433/487b4fb6-83e3-11e6-9f2d-56c6817709bd.png)

I'll open a separate issue regarding the loss of this specialisation in the exported XML

**Comment by wolandscat** [comment]
This is because I have not implemented 'anchored types' in BMM, nor have I compensated for their lack by manually overriding attributes like normal_range where they should be overridden. We should actually fix the BMM, which is easy enough to do. See e.g. https://github.com/openEHR/reference-models/blob/master/models/openEHR/Release-1.0.3/BMM/openehr_basic_types_103.bmm#L530
